services:
  fastapi_service:
    build:
      context: .
      dockerfile: Dockerfile
    image: ipni_image
    environment:
      CONNECTION_STR: "mysql+pymysql://root:root_passwd@mysql_service/ipni"
    ports:
      - 8080:81
    depends_on:
      - mysql_service

  phpmyadmin:
    image: docker.io/phpmyadmin/phpmyadmin:latest
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql_service
      PMA_PORT: 3306
    depends_on:
      - mysql_service

  mysql_service:
    image: docker.io/library/mysql:8
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_passwd
      - MYSQL_DATABASE=ipni
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_passwd
    volumes:
      - mysql_service_data:/var/lib/mysql

volumes:
  mysql_service_data:
