version: "1.0"
name: biokb_ipni
# for dev: podman-compose --env-file .env_template up -d

services:
  api:
    build: .
    container_name: biokb_ipni
    environment:
      CONNECTION_STR: ${CONNECTION_STR}
      NEO4J_URI: ${NEO4J_URI}
      IPNI_API_USERNAME: ${IPNI_API_USERNAME}
      IPNI_API_PASSWORD: ${IPNI_API_PASSWORD}
    ports:
      - ${IPNI_API_PORT}:8000
    volumes:
      - ~/.biokb/ipni:/root/.biokb/ipni

networks:
  default:
    name: biokb_network
    external: true