version: "0.1"
name: biokb_ipni

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: ipni_image
    environment:
      CONNECTION_STR: "mysql+pymysql://biokb_user:biokb_passwd@mysql/biokb?charset=utf8mb4"
    ports:
      - 8080:8000
    depends_on:
      - mysql

  pma:
    image: docker.io/phpmyadmin/phpmyadmin:5.2.1
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    depends_on:
      - mariadb

  mysql:
    image: docker.io/library/mysql:8.4.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_passwd
      - MYSQL_DATABASE=biokb
      - MYSQL_USER=biokb_user
      - MYSQL_PASSWORD=biokb_passwd
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

volumes:
  mariadb_data:
